env:
  global:
    - DOCKER_VERSION=17.03.0~ce-0~debian-jessie
    - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  # Install docker
  - sudo apt-get install apt-transport-https ca-certificates curl python-software-properties
  - sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install docker-ce=17.03.0~ce-0~debian-jessie
  - sudo docker run hello-world
  - docker -v
  - docker-compose -v

  # Install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose run --rm --no-deps web echo 'Gems now pre-installed.'
  # Use 'run ...` instead of 'exec ...` so that entrypoint's customized bundle install runs completely.
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
  # The detached `up` also runs entrypoint — but because it's detached,
  # bundle install doesn't finish before shell moves on to next commands.
  - docker ps
  - docker-compose exec web rails db:setup

script:
  - docker-compose exec web rails test

before_cache:
  - docker-compose logs > ./log/docker-ci.log
  - docker-compose exec web rails tmp:clear
  - docker-compose down

deploy:
  provider: heroku
  on: master
  app: jfmk-auth-staging
  api_key:
    secure: VFq4RjzrBs77MxsBETeIJv65PoGkbFIOyyKAdraoZ3tC9CTiYvST8clmMu5ai/U349NCoH9oPhRxAsmvcq9DNF5/KDdq7/qeL6XaIhV2lwhqt9GgA834gepapTOuaONjNKzCqo3UDRNf8gei6xBbdH7Jd6BFIqyLHDu3jLRym91InXu8LMq4nm2RKeQPIxj1cOcg5eH0R0kS9oubjtUDO9zufsbTQ+jRNP8LnncoQhT4+pYJAI8C7d9PD9QVVmPtKSR7H6IFz7DDPmvUkZ0IfuskYWeSO5XIejGLtSgUWTboQXjCy3HEew4XhfrapR91QAMJSdBMwE8DezX/RrVGEzT/Qiq8zYMIdGEqnwH6wHl8KHlcp0e+R1SDqOIe5JMSCddkv/Y2VqfAprwaYRMHBA2AzFhgEUH5NgNSy9w8TSPyBiEwLWc9ZrvrrYQ7G9tJQHw0fOromNww9ewF84rfh07VD3wV0hVsU+F1MCngNX/teyyV7Qjf5ukCYTFiLMKQYmGZr5SHJUGtFDe0wwDMWgKRFvOMTzxw7eJycelPiqMn5dJb/c8l2y4XmWVV3/oDpVCVxae1eEtPbp2mAxPdRa/k7yqhH1kQ0uVC8Mqcuzh7LjPYZOW7vMUAJQ1Y33tdewza9fTLcU74Is98AoQCh4rnoOHMdF6cioAAgbrp54U=
  before_deploy:
    - 'rails db:migrate'
    - 'rails db:schema:cache:clear'
    - 'rails assets:precompile'
    - restart

# For travis beta cache feature, might need to expose bundler vendor/cache
# as a volume in docker-compose in order to leverage this feature
#cache: true
#before_cache:
#  - docker-compose exec test bundle clean
