language: ruby

rvm:
  - 2.3

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.1

before_install:
  - docker -v
  - docker-compose -v
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - docker -v
  - docker-compose -v

  # Once travis supports same version, the following can be removed
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v

install:
  - docker-compose build
  - docker-compose exec test rails r bin/setup
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
  - docker ps

script:
  - docker-compose exec test rails test

after_script:
  - docker-compose down
