language: ruby

rvm:
  - 2.3

services:
  - docker

addons:
  artifacts:
    paths:
      - './log'

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  - docker -v
  - docker-compose -v
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - docker -v
  - docker-compose -v

  # Once travis supports same version, the following can be removed
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
  - docker ps
  - docker-compose exec test rails r bin/setup

script:
  - docker-compose exec test rails test

before_cache:
  - docker-compose down

after_script:
  - docker-compose down
  - docker-compose logs > ./log/docker-ci.log

deploy:
  provider: heroku
  on: master
  app: jfmk-auth-staging
  api_key:
    secure: VFq4RjzrBs77MxsBETeIJv65PoGkbFIOyyKAdraoZ3tC9CTiYvST8clmMu5ai/U349NCoH9oPhRxAsmvcq9DNF5/KDdq7/qeL6XaIhV2lwhqt9GgA834gepapTOuaONjNKzCqo3UDRNf8gei6xBbdH7Jd6BFIqyLHDu3jLRym91InXu8LMq4nm2RKeQPIxj1cOcg5eH0R0kS9oubjtUDO9zufsbTQ+jRNP8LnncoQhT4+pYJAI8C7d9PD9QVVmPtKSR7H6IFz7DDPmvUkZ0IfuskYWeSO5XIejGLtSgUWTboQXjCy3HEew4XhfrapR91QAMJSdBMwE8DezX/RrVGEzT/Qiq8zYMIdGEqnwH6wHl8KHlcp0e+R1SDqOIe5JMSCddkv/Y2VqfAprwaYRMHBA2AzFhgEUH5NgNSy9w8TSPyBiEwLWc9ZrvrrYQ7G9tJQHw0fOromNww9ewF84rfh07VD3wV0hVsU+F1MCngNX/teyyV7Qjf5ukCYTFiLMKQYmGZr5SHJUGtFDe0wwDMWgKRFvOMTzxw7eJycelPiqMn5dJb/c8l2y4XmWVV3/oDpVCVxae1eEtPbp2mAxPdRa/k7yqhH1kQ0uVC8Mqcuzh7LjPYZOW7vMUAJQ1Y33tdewza9fTLcU74Is98AoQCh4rnoOHMdF6cioAAgbrp54U=
  before_deploy:
    - 'rails db:migrate'
    - 'rails db:schema:cache:clear'
    - 'rails assets:precompile'
    - restart
