version: '2.1'

services:
  # https://unboxed.co/blog/docker-re-bundling/
  bundle_cache:
    command: "echo 'bundle_cache service is going to start and then immediately exit since it is just a volume.'"
    image: alpine:latest
    volumes:
      - 'bundle_cache:/bundle'

  web:
    depends_on:
      - bundle_cache
      - postgres
    build: .
    env_file: .env
    command: >
      bash -c "
        # Run test server detached without tail log
        RAILS_ENV=test bundle exec puma -b tcp://0.0.0.0:3001 -d &&
        # Run web server and tail the log
        bundle exec puma -C config/puma.rb
        "
    environment:
      - BUNDLE_PATH=/bundle
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=web
      - TEST_PORT=3001
    volumes:
      - '.:/jfmk_auth'
    volumes_from:
      - bundle_cache
    # Allow interaction on detached sessions like byebug
    stdin_open: true
    tty: true

  postgres:
    image: 'postgres:9.6.1'
    environment:
      POSTGRES_USER: 'jfmk_auth'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    logging:
      driver: 'none'

  selenium:
    #image: selenium/standalone-firefox-debug:2.48.2
    image: selenium/standalone-chrome-debug:3.0.1-germanium # :2.27 not working
    logging:
      driver: 'none'

volumes:
  postgres:
  bundle_cache:
