version: '3.1'

services:
  postgres:
    image: 'postgres:9.6.1'
    environment:
      POSTGRES_USER: 'jfmk_auth'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    logging:
      driver: 'none'

  web:
    depends_on:
      - postgres
    build: .
    env_file: .env
    volumes:
      - '.:/jfmk_auth'

    # Allow interaction on detached sessions like byebug
    stdin_open: true
    tty: true

  test:
    build: .
    env_file: .env
    environment:
      - RAILS_ENV=test
      - TEST_APP_HOST=test
      - PORT=3001
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    volumes:
      - '.:/jfmk_auth'
    depends_on:
      - postgres
      - selenium

    # Allow interaction on detached sessions like byebug
    stdin_open: true
    tty: true

  selenium:
    #image: selenium/standalone-firefox-debug:2.48.2
    image: selenium/standalone-chrome-debug:3.0.1-germanium # :2.27 not working
    logging:
      driver: 'none'

volumes:
  postgres:
