version: '2.1'

services:
  postgres:
    image: 'postgres:9.6.1'
    environment:
      POSTGRES_USER: 'jfmk_auth'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    logging:
      driver: 'none'

  web:
    depends_on:
      - postgres
    build: .
    volumes:
      - '.:/jfmk_auth'

    # Allow interaction on detached sessions like byebug
    stdin_open: true
    tty: true

  test:
      build: .
      environment:
        - BIND_ON=0.0.0.0
        - PORT=3001
        - RAILS_ENV=test
        - SELENIUM_HOST=selenium
        - TEST_APP_HOST=test
      volumes:
        - '.:/jfmk_auth'
      depends_on:
        - postgres
        - selenium

      # Allow interaction on detached sessions like byebug
      stdin_open: true
      tty: true

  selenium:
    #image: selenium/standalone-firefox-debug:2.48.2
    image: selenium/standalone-chrome-debug:3.0.1-germanium # :2.27 not working
    logging:
      driver: 'none'

volumes:
  postgres:
