version: '2.1'

services:
  postgres:
    expose:
      - 5432

  web:
    expose:
      - 3000

  test:
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY
      expose:
        - 3001

  selenium:
      expose: [4444, 5900]
