version: '3.1'

services:
  postgres:
    expose: [5432] # Not exposing port externally because it conflicts a port used by Travis

  web:
    command: bash -c "RAILS_ENV=test puma -b tcp://0.0.0.0:3001"
    expose: [3001]

  selenium:
    expose: [4444, 5900]
